a = {
    "bag": [
        "**Roupas**:\n   - Camisetas leves ou blusas de manga curta\n   - Calças leves ou bermudas\n   - Um moletom ou jaqueta leve para as noites mais frescas\n   - Roupas íntimas e meias",
        "**Calçados**:\n   - Tênis confortável para caminhadas\n   - Sandálias ou chinelos para relaxar",
        "**Outros**:\n   - Protetor solar\n   - Óculos de sol\n   - Guarda-chuva ou capa de chuva (caso de dias com previsão de chuva)\n   - Mochila pequena para carregar itens pessoais durante os passeios\n   - Carregador portátil para dispositivos eletrônicos\n   - Câmera fotográfica ou celular para registrar momentos\n   - Guia de Nova Iorque ou aplicativo de turismo para facilitar a navegação e descoberta cultural",
    ],
    "climate": [
        "Em junho, o clima em Nova Iorque é geralmente agradável, com temperaturas médias que variam de 20°C a 27°C. A média das temperaturas máximas é de aproximadamente 27°C, enquanto a média das temperaturas mínimas é de cerca de 18°C.\n\nJunho é considerado um mês relativamente seco em Nova Iorque, mas pode ocorrer algumas chuvas esparsas. Não é um mês de desastres climáticos na cidade."
    ],
    "culinary": [
        "A culinária típica de Nova Iorque é caracterizada pela diversidade cultural e pela influência de imigrantes de diferentes partes do mundo. A cidade é famosa por seus pratos icônicos que variam de alimentos de rua a refeições sofisticadas. Os sabores são intensos e muitas vezes refletem a mistura de tradições culinárias.",
        "1. New York Cheesecake\n   - O New York Cheesecake é um bolo cremoso e denso, geralmente feito com queijo crema, açúcar, ovos e uma crosta de biscoito. É uma das sobremesas mais famosas da cidade.",
        "2. Bagel com Cream Cheese\n   - O bagel é um pão em formato de anel, frequentemente servido com cream cheese. É uma opção popular para o café da manhã e pode ser encontrado em diversas variações.",
        "3. Pizza de Nova Iorque\n   - A pizza de Nova Iorque é conhecida por sua base fina e crocante, com bordas macias. Geralmente, é servida em fatias grandes, podendo ser coberta com molho de tomate e queijo.",
        "4. Hot Dog de Rua\n   - Os hot dogs de rua são uma parte essencial da culinária de Nova Iorque, muitas vezes servidos com cebolas, mostarda, ketchup e relish. Eles são uma popular comida rápida disponível nas barracas espalhadas pela cidade.",
        "5. Dumplings\n   - Devido à grande influência da imigração asiática, os dumplings são um prato popular que pode ser encontrado em muitos restaurantes. São pequenas massas recheadas com carne ou vegetais, cozidas no vapor ou fritas.",
    ],
    "emergency": [
        "**Números de Emergência:**\n1. **Polícia**: 911\n2. **Bombeiros**: 911\n3. **Ambulância**: 911",
        "**Funcionamento dos Serviços de Emergência:**\n- Em Nova Iorque, os serviços de emergência operam através do número 911, que é utilizado para relatar qualquer situação que necessite de assistência de polícia, bombeiros ou serviços médicos. A chamada é atendida por operadores treinados, que podem direcionar a chamada para o serviço apropriado. Os serviços são disponíveis 24 horas por dia, todos os dias, e as respostas são rápidas e eficientes.",
        "**Qualidade, Confiabilidade e Custo:**\n- Os serviços de emergência em Nova Iorque são considerados de alta qualidade e confiáveis. Os bombeiros e paramédicos recebem treinamento rigoroso e médicos altamente qualificados fazem parte das equipes de ambulância. Embora o atendimento inicial seja gratuito, alguns serviços médicos, como o transporte de ambulância, podem envolver custos que variam dependendo do seguro e das circunstâncias do atendimento.",
    ],
    "history": [
        "Nova Iorque, uma das cidades mais icônicas do mundo, é conhecida por sua diversidade cultural e sua influência global em áreas como arte, moda e negócios. Fundada em 1624 como uma colônia holandesa chamada Nova Amsterdã, a cidade se tornou um importante centro de imigração e comércio. A cultura nova-iorquina é marcada pela presença de famosos museus, teatros e uma rica cena musical que reflete a mistura de tradições de seus habitantes."
    ],
    "itinerary": [
        "**Dia 1: Explorando a Cultura de Manhattan**\n- **Manhã:**\n  - Comece o dia no **Museu de Arte Moderna (MoMA)**. A entrada é gratuita às sextas-feiras à tarde, então planeje sua visita nesse horário. Aprecie obras de artistas renomados.\n- **Tarde:**\n  - Após o MoMA, caminhe até o **Central Park**. Aproveite para relaxar e fazer um piquenique, observando a natureza e a arquitetura ao redor. Explore o **Belvedere Castle** e a **Bethesda Terrace**.\n- **Noite:**\n  - Para o jantar, experimente uma pizza em uma das muitas pizzarias locais, como a **Joe's Pizza**. Depois, caminhe pela **Times Square**, aproveitando as luzes e a energia do local.",
        "**Dia 2: Museus e História**\n- **Manhã:**\n  - Visite o **Museu Americano de História Natural**. É um lugar excelente para aprender sobre ciência e cultura, com várias exposições interessantes. A entrada é por doação, permitindo que você contribua de acordo com seu orçamento.\n- **Tarde:**\n  - Após o museu, dirija-se ao **The High Line**, um parque elevado construído sobre antigas linhas de trem. Caminhe e aprecie a arte ao ar livre e as vistas da cidade.\n- **Noite:**\n  - Para finalizar a viagem, jante no **Chelsea Market**, onde você poderá encontrar várias opções de comida a preços acessíveis e aproveitar o ambiente animado.",
    ],
    "quick": ["inglês", "dólar americano", "Estados Unidos", "GMT-5"],
    "transportation": [
        "Em Nova Iorque, a locomoção é facilitada por um extenso sistema de transporte público e opções de transporte privado. Os principais meios de transporte incluem:\n\n1. **Metrô**: O sistema de metrô de Nova Iorque é uma das maneiras mais rápidas e econômicas de se locomover pela cidade. Ele funciona 24 horas por dia e cobre as áreas principais. Para utilizá-lo, o turista deve comprar um cartão MetroCard em máquinas disponíveis nas estações. Há duas opções de pagamento:\n   - **Pay-Per-Ride**: Para cada viagem, o usuário paga uma tarifa única.\n   - **Unlimited Ride**: Permite viagens ilimitadas em 7 dias (não disponível por 2 dias).\n   \n2. **Ônibus**: Complementando o metrô, os ônibus também são uma boa opção, especialmente para trajetos mais curtos ou que não são atendidos pela rede de metrô. O uso do MetroCard nos ônibus também é aceito.\n\n3. **Bicicletas**: O serviço de aluguel de bicicletas, conhecido como Citi Bike, está disponível. É uma boa forma de explorar áreas como o Central Park e ao longo dos rios. O usuário pode adquirir passes para 1 dia ou 3 dias.\n\n4. **Caminhadas**: Nova Iorque é uma cidade altamente acessível para pedestres. Muitas atrações estão localizadas próximas umas das outras, e caminhar pode ser uma experiência agradável.\n\n5. **Táxis e serviços de carona**: Os táxis amarelos são uma opção conveniente, embora mais cara. Também é possível usar aplicativos como Uber e Lyft.\n\n**Transporte dos aeroportos**:\n- **Aeroporto JFK**: A linha de metrô AirTrain conecta o aeroporto à linha A do metrô, que leva a Manhattan. O custo do AirTrain é de $8, além da tarifa do metrô. Alternativamente, táxis estão disponíveis, com uma tarifa fixa de cerca de $70 até Manhattan.\n- **Aeroporto LaGuardia**: É acessível através de ônibus locais, como o Q70, que leva a estações de metrô em Queens. Táxis também estão disponíveis, com preços variando dependendo do destino.\n- **Aeroporto Newark**: O AirTrain Newark conecta o aeroporto à estação de trem de Newark, onde é possível pegar o NJ Transit ou um trem de Amtrak para Manhattan. O custo do AirTrain é de $8, além da tarifa do trem.\n\nAo utilizar o transporte público, é importante manter a segurança e seguir as orientações nas estações. Com essas opções, o usuário poderá explorar Nova Iorque de forma tranquila e acessível."
    ],
    "visa": [
        "O usuário brasileiro que viajará para Nova Iorque, Nova Iorque, Estados Unidos da América, deverá obter um visto ou uma autorização de viagem. Nesse caso, é recomendável solicitar o ESTA (Electronic System for Travel Authorization), que é um tipo de autorização para viagens de curto prazo sob o Programa de Isenção de Vistos (Visa Waiver Program), se a viagem for por turismo ou negócios e durar até 90 dias. Além disso, o passaporte deve ser válido por pelo menos seis meses além da data da entrada nos EUA. É importante verificar essas informações e realizar o processo de solicitação com antecedência."
    ],
    "warnings": [
        "Cuidados e Riscos:\n   - Mantenha sempre seus objetos de valor, como celular e carteira, em locais seguros e evite exibi-los em público.\n   - Cuidado ao atravessar as ruas, pois o tráfego em Nova Iorque é intenso e predominantemente com carros vindo da esquerda.\n   - Esteja atento ao seu entorno, especialmente em áreas menos movimentadas e à noite.",
        "Diferenças Culturais:\n   - Os nova-iorquinos podem parecer mais diretos e menos amigáveis do que os brasileiros, mas isso é muitas vezes uma questão de cultura e não de antipatia.\n   - A pontualidade é valorizada, então é recomendado cumprir horários em compromissos e eventos.\n   - O trocador de dinheiro aceitável em estabelecimentos é preferido em vez do uso de moeda local em algumas situações.",
        "Cuidados Especiais:\n   - Mulheres devem ter cuidado extra ao andar sozinhas à noite; evite áreas isoladas e prefira locais com iluminação e movimento.\n   - Crianças devem ser supervisionadas continuamente e, se possível, use uma pulseira de identificação com nome e número de contato.\n   - Para minorias, é importante estar ciente das normas de respeito e inclusão, e procurar informações sobre comunidades que promovem um ambiente acolhedor.",
    ],
    "destination": "Nova Iorque, Nova Iorque, Estados Unidos da América",
    "lat": "",
    "lon": "",
}
